name: CI/CD Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker build . -t my-image
        docker push my-image

    - name: Set output
      run: echo "image_tag=my-image" >> $GITHUB_OUTPUT

    - name: Deploy
      run: |
        echo "Deploying image with tag $(cat $GITHUB_OUTPUT | grep image_tag | cut -d '=' -f2)"
