name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker_login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        env:
          DOCKER_STATE: ${{ env.GITHUB_STATE }}
          DOCKER_OUTPUT: ${{ env.GITHUB_OUTPUT }}

      - name: Handle failure
        if: failure()
        run: |
          from sweepai.handlers.on_check_suite import download_logs, clean_logs
          import os
          import json

          run_id = os.environ['GITHUB_RUN_ID']
          repo_full_name = json.loads(os.environ['GITHUB_REPOSITORY'])
          installation_id = json.loads(os.environ['GITHUB_INSTALLATION_ID'])

          logs = download_logs(repo_full_name, run_id, installation_id)
          logs, user_message = clean_logs(logs)
          print(f"::error ::{user_message}")
        shell: python
